linters:
  enable:
    - lll
linters-settings:
  lll:
    line-length: 80
  govet:
    disable:
      - composites
issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate |^\\s*// "
